# Generated by Django 5.2.11 on 2026-02-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='asset_class',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('equity', 'Equity'), ('forex', 'Forex')], default='crypto', max_length=10),
        ),
        migrations.AddField(
            model_name='screenresult',
            name='asset_class',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('equity', 'Equity'), ('forex', 'Forex')], default='crypto', max_length=10),
        ),
    ]
