# Generated by Django 5.2.11 on 2026-02-24 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_backtestresult_asset_class_screenresult_asset_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('asset_class', models.CharField(choices=[('crypto', 'Crypto'), ('equity', 'Equity'), ('forex', 'Forex')], default='crypto', max_length=10)),
                ('is_template', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_interval_seconds', models.IntegerField(blank=True, null=True)),
                ('schedule_enabled', models.BooleanField(default=False)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('api', 'API')], default='manual', max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('current_step', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=0)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_run', to='analysis.backgroundjob')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='analysis.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('step_type', models.CharField(max_length=50)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('condition', models.CharField(blank=True, default='', max_length=200)),
                ('timeout_seconds', models.IntegerField(default=300)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='analysis.workflow')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('workflow', 'order')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('condition_met', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='analysis.workflowstep')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='analysis.workflowrun')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
