# Generated by Django 5.2.11 on 2026-02-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_workflow_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='backgroundjob',
            index=models.Index(fields=['status', '-created_at'], name='idx_job_status_created'),
        ),
        migrations.AddIndex(
            model_name='backtestresult',
            index=models.Index(fields=['asset_class', 'strategy_name'], name='idx_backtest_asset_strategy'),
        ),
        migrations.AddIndex(
            model_name='backtestresult',
            index=models.Index(fields=['framework', 'asset_class'], name='idx_backtest_framework_asset'),
        ),
        migrations.AddIndex(
            model_name='backtestresult',
            index=models.Index(fields=['symbol', 'timeframe'], name='idx_backtest_symbol_tf'),
        ),
        migrations.AddIndex(
            model_name='screenresult',
            index=models.Index(fields=['asset_class', '-created_at'], name='idx_screen_asset_created'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['workflow', '-created_at'], name='idx_wfrun_workflow_created'),
        ),
    ]
