# Generated by Django 5.2.11 on 2026-02-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_tradechecklog_asset_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskLimitChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.IntegerField(db_index=True)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.CharField(max_length=50)),
                ('new_value', models.CharField(max_length=50)),
                ('changed_by', models.CharField(default='', max_length=150)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['portfolio_id', '-created_at'], name='idx_alert_portfolio_created'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['severity', '-created_at'], name='idx_alert_severity_created'),
        ),
        migrations.AddIndex(
            model_name='tradechecklog',
            index=models.Index(fields=['portfolio_id', '-checked_at'], name='idx_tradecheck_portfolio_time'),
        ),
        migrations.AddIndex(
            model_name='risklimitchange',
            index=models.Index(fields=['portfolio_id', '-changed_at'], name='idx_risklimitchange_port_time'),
        ),
    ]
