# Generated by Django 5.2.11 on 2026-02-23 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_exchangeconfig_datasourceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourceconfig',
            name='asset_class',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('equity', 'Equity'), ('forex', 'Forex')], default='crypto', max_length=10),
        ),
        migrations.AddField(
            model_name='exchangeconfig',
            name='asset_class',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('equity', 'Equity'), ('forex', 'Forex')], default='crypto', max_length=10),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='asset_class',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('equity', 'Equity'), ('forex', 'Forex')], db_index=True, default='crypto', max_length=10),
        ),
        migrations.AlterField(
            model_name='datasourceconfig',
            name='exchange_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='market.exchangeconfig'),
        ),
        migrations.AlterField(
            model_name='exchangeconfig',
            name='exchange_id',
            field=models.CharField(choices=[('binance', 'Binance'), ('coinbase', 'Coinbase'), ('kraken', 'Kraken'), ('kucoin', 'KuCoin'), ('bybit', 'Bybit'), ('yfinance', 'Yahoo Finance')], max_length=50),
        ),
    ]
