# Generated by Django 5.2.11 on 2026-02-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_marketdata_uniq_marketdata_symbol_exchange_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeconfig',
            name='key_rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
