# Generated by Django 5.2.11 on 2026-03-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_exchangeconfig_key_rotated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(default='1h', max_length=10)),
                ('opportunity_type', models.CharField(choices=[('volume_surge', 'Volume Surge'), ('rsi_bounce', 'RSI Bounce'), ('breakout', 'Breakout Candidate'), ('trend_pullback', 'Trend Pullback'), ('momentum_shift', 'Momentum Shift')], db_index=True, max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('acted_on', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-score', '-detected_at'],
                'indexes': [models.Index(fields=['opportunity_type', '-score'], name='market_mark_opportu_c8b187_idx'), models.Index(fields=['-detected_at', 'expires_at'], name='market_mark_detecte_5b6ad5_idx')],
            },
        ),
    ]
