# Generated by Django 5.2.11 on 2026-03-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_market_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketopportunity',
            name='asset_class',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('equity', 'Equity'), ('forex', 'Forex')], db_index=True, default='crypto', max_length=10),
        ),
        migrations.AddIndex(
            model_name='marketopportunity',
            index=models.Index(fields=['asset_class', '-score'], name='market_mark_asset_c_3bbb3c_idx'),
        ),
    ]
