# Generated by Django 5.2.11 on 2026-02-18 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFillEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_price', models.FloatField()),
                ('fill_amount', models.FloatField()),
                ('fee', models.FloatField(default=0.0)),
                ('fee_currency', models.CharField(blank=True, default='', max_length=20)),
                ('exchange_trade_id', models.CharField(blank=True, default='', max_length=100)),
                ('filled_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-filled_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='avg_fill_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='fee_currency',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='filled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode',
            field=models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], default='paper', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='portfolio_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='reject_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='stop_loss_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('open', 'Open'), ('partial_fill', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('error', 'Error')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['exchange_id', 'exchange_order_id'], name='idx_order_exchange'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['symbol', 'status'], name='idx_order_symbol_status'),
        ),
        migrations.AddField(
            model_name='orderfillevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_events', to='trading.order'),
        ),
    ]
