# Generated by Django 5.2.11 on 2026-02-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_production_hardening_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='asset_class',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('equity', 'Equity'), ('forex', 'Forex')], default='crypto', max_length=10),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['asset_class', 'symbol'], name='idx_order_asset_symbol'),
        ),
    ]
