# Generated by Django 5.2.11 on 2026-02-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_order_asset_class_order_idx_order_asset_symbol'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['portfolio_id', 'status', '-timestamp'], name='idx_order_portfolio_status_ts'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='idx_order_created_desc'),
        ),
    ]
