# Generated by Django 5.2.11 on 2026-02-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.IntegerField(unique=True)),
                ('telegram_enabled', models.BooleanField(default=True)),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('on_order_submitted', models.BooleanField(default=True)),
                ('on_order_filled', models.BooleanField(default=True)),
                ('on_order_cancelled', models.BooleanField(default=True)),
                ('on_risk_halt', models.BooleanField(default=True)),
                ('on_trade_rejected', models.BooleanField(default=True)),
                ('on_daily_summary', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'notification preferences',
            },
        ),
    ]
